AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: api
Resources:
  PutFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.lambda_handler
      Runtime: python3.6
      CodeUri: s3://aws-sam-example/633e257ee8edbcc288b426e3761c944a
      Timeout: 900
      Tracing: Active
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSCloudFormationFullAccess
      - CloudWatchFullAccess
      MemorySize: 128
      Events:
        GetAllResource:
          Type: Api
          Properties:
            Path: /
            Method: get
            RequestParameters:
            - method.request.querystring.start:
                Required: true
                Caching: true
            - method.request.querystring.end:
                Required: true
                Caching: true
